version: "3"
services:
  nginx:
    container_name: my_nginx
    image: nginx:1.13.3-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - uwsgi
    networks:
      - myapp
  uwsgi:
    container_name: my_uwsgi
    build:
      context: ./
      dockerfile: ./uwsgi/Dockerfile
    command: uwsgi /uwsgi.ini --py-autoreload 3
    volumes:
      - ./:/usr/src/app
      - ./uwsgi/uwsgi.ini:/uwsgi.ini
    networks:
      - myapp
      
networks:
  myapp:
    driver: bridge
